### PR TITLE
Properties parser skiping of untranslated properties

### PR DESCRIPTION
**Pull request by dragosv**
At this point the properties parser outputs the original translation even when there is no translation and leave_untranslated_blank  is YES (therefore empty string comes back from the callback). Added a new property called skip_untranslated to the parser that would make the whole property including comments to be skipped.

### CODE REVIEW

**Comment by iafan** [comment]
In which situation is this necessary?

Note that Serge has the way of dealing with this: One can set `leave_untranslated_blank   NO` in the config (see [here](https://serge.io/docs/configuration-files/reference/#sel:I2NvZGVfMC9zcGFuLjk1MjYvQC0jY29kZV8wL3NwYW4uOTU1NC9AOjI)) and then use [replace_strings](https://serge.io/docs/plugins/callback/replace_strings/) plugin to remove empty translations.

**Comment by dragosv** [comment]
Even if leave_untranslated_blank is YES, meaning a blank string comes back the translation is not emptied (there is a condition to replace the source translation only if the string is not blank, so no change is made)

**Comment by dragosv** [comment]
The issue can be seen in t/data/engine/parse_properties/01-untranslated test

**Comment by dragosv** [comment]
Also there is t/data/engine/parse_properties/00 that uses the default for leave_untranslated_blank (NO)

**Comment by iafan** [comment]
I'm not sure I follow... I guess I can rephrase my questions as: in which situations (on which platforms) one would strictly need .properties files to have untranslated keys omitted? One key strength of Serge is that it always provides English fallbacks when no translation is present, which means one usually doesn't have to think about implementing any fallback mechanisms in the code. Also, Serge tries to produce exactly the same resource file structure, so removing the keys is not something Serge currently does in any parser. This simplifies the parser code and increases the compatibility with file format dialects.

Speaking of the regex, it should be rather easy to implement one for strings like `key = ""`. This is something that the engineer who creates the .serge config would do explicitly, making sure that the modified file meets their expectations.

**Comment by dragosv** [comment]
This is required in order to determine if strings have been translated or not as sometimes the source translation is the proper one, so a rule that source equal target means untranslated does not work. Also the properties parser does not support outputting empty strings like other parsers.

**Pull request closed without merging**
